### PR TITLE
upgrade FMDB version used

### PR DESCRIPTION
**Pull request by qingqingliu**
@bhariharan review pleae

### CODE REVIEW

**Comment by wmathurin** [comment]
What version/tag are we based on now?

**Comment by khawkins** [comment]
Something older than what we have.  If you diff our current merge-base (70dd7f7ee057a3781049f69ac09b18e15e7bf1be) with the HEAD of `master` in the upstream repo, there are only minor changes.

**Comment by khawkins** [comment]
To clarify, our current FMDB base is newer than the version in this PR.  Unless there's compelling functionality here that needs to be retroactively re-applied to our current version of FMDB, we should stick with what we have.

**Comment by jeanbovet** [comment]
We did the update because we couldn't apply the proper level of protection to the old code we had. So anything newer should be fine IMO.

**Comment by bhariharan** [comment]
@qingqingliu We should probably keep the newer version in current ```Mobile SDK```.

**Comment by bhariharan** [comment]
Also, the branch we use here is ```sdk```. It has some extra logging, but not much else that's different in the fork I believe.

**Comment by qingqingliu** [comment]
Thanks all. Will close this

**Pull request closed without merging**
